const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {JSDOM}=require('C:/Users/auror/Downloads/fivecred.com.br-main/node_modules/jsdom');
const {chromium}=require('C:/Users/auror/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'..'),output=path.join(root,'public-site');
const manifest=JSON.parse(fs.readFileSync(path.join(root,'work/pages-manifest.json')));
const read=file=>fs.readFileSync(path.join(output,file),'utf8');
function walk(folder){return fs.readdirSync(folder,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(folder,e.name)):[path.join(folder,e.name)]);}
const allFiles=walk(output),htmlFiles=allFiles.filter(p=>p.endsWith('.html'));
const forbidden=/prévia|demonstração|versão local|não publicada|reformulações|pauta prevista|estrutura editorial|dados fictícios|conteúdos serão preparados/i;
for(const file of htmlFiles){const doc=new JSDOM(fs.readFileSync(file,'utf8'),{url:'http://local/'+path.relative(output,file).replaceAll('\\','/')}).window.document;assert(!forbidden.test(doc.body.textContent),file+' prototype copy');assert(!doc.querySelector('.preview,.portal-group,[data-placeholder]'),file+' prototype controls');assert.equal(doc.querySelector('meta[name=robots]').content,'index,follow');for(const a of doc.querySelectorAll('a[href]')){const u=new URL(a.href);if(u.hostname!=='local')continue;const target=path.join(output,u.pathname.endsWith('/')?u.pathname+'index.html':u.pathname);assert(fs.existsSync(target),file+' broken '+u.pathname);}}
for(const file of allFiles)assert(!/(?:^|[\\/])(?:work|tests|docs|node_modules|app|fivecred-marketplace-[^\\/]+)(?:[\\/]|$)/.test(path.relative(output,file)),'Private output '+file);
assert(read('index.html').includes('class="simulation-cta"'));
assert(read('fivecred-next/simulacao.html').includes('data-connected-form="home"'));
assert.equal(new JSDOM(read('index.html')).window.document.querySelector('h1').textContent,'Crédito para tirar seus planos do papel.');
(async()=>{
 const server=http.createServer((req,res)=>{const url=new URL(req.url,'http://local');const relative=decodeURIComponent(url.pathname)+(url.pathname.endsWith('/')?'index.html':'');const file=path.resolve(output,'.'+relative);if(!file.startsWith(output+path.sep)){res.writeHead(403);return res.end();}fs.readFile(file,(e,b)=>{if(e){res.writeHead(404);return res.end();}res.setHeader('Content-Type',({'.html':'text/html; charset=utf-8','.css':'text/css','.js':'text/javascript','.png':'image/png','.webp':'image/webp','.svg':'image/svg+xml','.woff2':'font/woff2'})[path.extname(file)]||'application/octet-stream');res.end(b);});});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;
 const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});const ctx=await browser.newContext({reducedMotion:'reduce'}),page=await ctx.newPage();let responseStatus=500;const posts=[],errors=[];
 await ctx.route('**/*',route=>{const req=route.request(),u=new URL(req.url());if(u.hostname==='127.0.0.1')return route.continue();if(u.hostname==='hook.us1.make.celonis.com'){posts.push({url:u.href,payload:req.postDataJSON()});return route.fulfill({status:responseStatus,body:responseStatus===200?'Accepted':'Error'});}errors.push('Unexpected request '+u.origin);return route.abort();});
 await ctx.addInitScript(()=>{window.open=url=>{window.__opened=url;return null;};});page.on('pageerror',e=>errors.push(e.message));
 try{
  for(const url of ['/',...manifest.map(p=>'/'+p.slug+'/index.html'),'/conteudos/index.html'])for(const width of [320,390,1440]){
   await page.setViewportSize({width,height:960});await page.goto(base+url);await page.evaluate(()=>document.fonts.ready);
   assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,url+' '+width+' overflow');assert(!forbidden.test(await page.locator('body').innerText()),url+' visible prototype text');
   const logo=await page.locator('.header .logo').getAttribute('href');assert.equal(new URL(logo,base+url).pathname,'/index.html');
   if(url==='/'&&width!==320){await page.screenshot({path:path.join(root,'tests/screenshots','production-home-'+width+'.png')});await page.locator('#seguranca').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(root,'tests/screenshots','production-photo-slot-'+width+'.png')});}
  }
  await page.goto(base+'/fivecred-next/simulacao.html');await page.waitForFunction(()=>document.querySelector('[data-connected-form]')?.dataset.formReady==='true');
  const form=page.locator('[data-connected-form]');await form.getByLabel('Nome completo',{exact:true}).fill('Teste Fivecred');await form.getByLabel('WhatsApp (com DDD)',{exact:true}).fill('11987654321');await form.getByLabel('CPF',{exact:true}).fill('12345678900');await form.getByLabel('Data de nascimento',{exact:true}).fill('01011990');await form.getByRole('button',{name:'Continuar →',exact:true}).click();await form.getByRole('radio',{name:'Trabalhador CLT',exact:true}).check();await form.getByRole('radio',{name:'Não',exact:true}).check();await form.getByRole('button',{name:'Continuar →',exact:true}).click();await form.getByLabel('Recebe benefício/salário em qual banco?',{exact:true}).fill('Banco teste');await form.getByRole('radio',{name:'R$ 1.000 a R$ 5.000',exact:true}).check();await form.getByRole('radio',{name:'Tarde',exact:true}).check();await form.getByRole('checkbox').nth(0).check();await form.getByRole('checkbox').nth(1).check();await form.locator('form').evaluate(f=>f.requestSubmit());await form.locator('.cf-error').waitFor();assert.equal(await form.locator('.cf-success').count(),0);responseStatus=200;await form.locator('form').evaluate(f=>f.requestSubmit());await form.locator('.cf-success').waitFor();assert.equal(posts.length,2);assert.equal(posts[0].url,posts[1].url);
  await page.goto(base+'/');await page.locator('.header [data-whatsapp]').click();const modal=page.locator('#whatsapp-contact-dialog');await modal.waitFor({state:'visible'});await modal.locator('[name=nome]').fill('Teste Fivecred');await modal.locator('[name=email]').fill('teste@example.com');await modal.locator('[type=submit]').click();assert((await page.evaluate(()=>window.__opened)).startsWith('https://wa.me/'));
  await page.goto(base+'/fivecred-landing-page/simulacao.html');assert(await page.locator('#leadForm fieldset[disabled]').count());assert(await page.locator('.form-unavailable').isVisible());
  await page.goto(base+'/lp-venda-carta-contemplada/simulacao.html');await page.locator('[data-choice="imovel"]').click();await page.locator('[name=administrator]').fill('Administradora teste');await page.locator('[data-journey] [type=submit]').click();await page.locator('[name=amount]').fill('100.000,00');await page.locator('[data-journey] [type=submit]').click();assert(await page.locator('[data-journey] button:disabled').isVisible());assert(await page.locator('.form-unavailable').isVisible());assert.equal(await page.locator('[data-journey] [data-action=whatsapp]').count(),0);
  for(const url of ['/work/build-sites.cjs','/tests/verify-sites.cjs','/fivecred-next/app/content.json','/fivecred-marketplace-imoveis/index.html','/fivecred-marketplace-veiculos/index.html'])assert.equal((await ctx.request.get(base+url)).status(),404);
  assert.deepEqual(errors,[]);const report={result:'PASS',htmlPages:htmlFiles.length,viewports:[320,390,1440],root:'General LP with CTA to the original form on a dedicated page',placeholders:'Photo/design slots preserved',homeWebhook:'HTTP error and retry checked with intercepted requests',pendingForms:'Blocked until dedicated webhooks are provided',realExternalSubmissions:0,errors};fs.writeFileSync(path.join(root,'tests/production-browser-results.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
 }finally{await browser.close();await new Promise(r=>server.close(r));}
})().catch(e=>{console.error(e);process.exit(1)});
