const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {chromium}=require('C:/Users/auror/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'..'),output=path.join(root,'public-site'),artifacts=path.join(root,'tests/screenshots');
const manifest=JSON.parse(fs.readFileSync(path.join(root,'work/pages-manifest.json')));
(async()=>{const server=http.createServer((req,res)=>{const u=new URL(req.url,'http://local'),f=path.join(output,u.pathname+(u.pathname.endsWith('/')?'index.html':''));fs.readFile(f,(e,b)=>{if(e){res.writeHead(404);return res.end();}res.setHeader('Content-Type',({'.html':'text/html; charset=utf-8','.css':'text/css','.js':'text/javascript','.woff2':'font/woff2','.png':'image/png','.webp':'image/webp','.svg':'image/svg+xml'})[path.extname(f)]||'application/octet-stream');res.end(b);});});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true}),ctx=await browser.newContext({reducedMotion:'reduce'}),page=await ctx.newPage(),rows=[],errors=[];await ctx.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());page.on('pageerror',e=>errors.push(e.message));
try{for(const slug of ['root',...manifest.map(p=>p.slug)])for(const width of [320,390,600,768,960,1024,1206,1279,1280,1440]){
 await page.setViewportSize({width,height:800});await page.goto(base+(slug==='root'?'/':'/'+slug+'/index.html'));await page.evaluate(()=>document.fonts.ready);
 const state=await page.evaluate(()=>{const rect=e=>{const r=e.getBoundingClientRect();return{left:r.left,right:r.right,width:r.width,height:r.height};};const header=document.querySelector('.header'),trust=document.querySelector('.trust-grid,.s-trust-grid'),hero=document.querySelector('.hero-grid,.s-hero-grid');return{width:innerWidth,overflow:document.documentElement.scrollWidth>innerWidth+1,menuVisible:getComputedStyle(document.querySelector('.menu-toggle')).display!=='none',heroColumns:getComputedStyle(hero).gridTemplateColumns.split(' ').length,trustColumns:getComputedStyle(trust).gridTemplateColumns.split(' ').length,hero:rect(hero),floatingPosition:getComputedStyle(document.querySelector('.floating-whatsapp')).position,headerHeight:rect(header).height,logoWidth:rect(header.querySelector('.logo')).width,headerOverflow:[...header.querySelectorAll('.logo,.button,.menu-toggle')].some(e=>{const r=rect(e);return r.width&&(r.left<0||r.right>innerWidth);}),legalTargets:[...document.querySelectorAll('.footer-bottom a')].map(e=>rect(e).height)};});
 rows.push({slug,...state});assert(!state.overflow&&!state.headerOverflow,slug+' '+width+' overflow');assert.equal(state.headerHeight,width<600?75:width<960?83:91,'Navbar height preserved');
 if(width<1280){assert(state.menuVisible,slug+' '+width+' compact navigation');assert.equal(state.heroColumns,1,slug+' '+width+' hero needs readable stacked layout');assert.equal(state.trustColumns,1,slug+' '+width+' trust needs full width');assert.equal(state.floatingPosition,'static',slug+' '+width+' WhatsApp must not overlap form');}else{assert.equal(state.heroColumns,2);assert.equal(state.trustColumns,2);}
 assert(state.legalTargets.every(h=>h>=44),'Comfortable footer touch areas');
 if(['root','lp-venda-carta-contemplada'].includes(slug)&&[390,1024,1206,1440].includes(width)){await page.screenshot({path:path.join(artifacts,'responsive-'+slug+'-hero-'+width+'.png')});await page.evaluate(()=>{document.querySelector('#seguranca').scrollIntoView({block:'start'});});await page.screenshot({path:path.join(artifacts,'responsive-'+slug+'-trust-'+width+'.png')});}
 }
 for(const [width,height] of [[320,568],[568,320],[844,390],[1024,600]]){await page.setViewportSize({width,height});await page.goto(base+'/');await page.locator('.menu-toggle').click();await page.locator('#main-nav summary').click();const last=page.locator('#main-nav>a').last();await last.scrollIntoViewIfNeeded();const b=await last.boundingBox();assert(b.y>=0&&b.y+b.height<=height,'Expanded menu stays usable in short viewport');await page.keyboard.press('Escape');await page.locator('.closing a').click();const top=await page.locator('#simulacao').evaluate(e=>e.getBoundingClientRect().top);const bottom=await page.locator('.header').evaluate(e=>e.getBoundingClientRect().bottom);assert(top>=bottom,'Form anchor clears navbar');}
 assert.deepEqual(errors,[]);const report={result:'PASS',pages:manifest.length+1,viewportChecks:rows.length,widths:[320,390,600,768,960,1024,1206,1279,1280,1440],smallLandscapeMenu:true,formsClearOfWhatsApp:true,navbarHeightPreserved:true,footerTouchTargets:'44px minimum',errors};fs.writeFileSync(path.join(root,'tests/responsive-layout-results.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
}finally{await browser.close();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e);process.exit(1)});
