module.exports=function applyFormCopy(pages){
 const details={
 'fivecred-next':['Preencha seus dados, conte seu perfil e informe o crédito que procura. A Fivecred orienta você sobre as possibilidades e as condições da análise.','Seus dados e seu perfil','Informe seus dados de contato, identificação e perfil para a solicitação.','O crédito que você procura','Indique banco, faixa de valor e melhor horário para conversar.'],
 'fivecred-landing-page':['Informe seus dados e seu perfil para solicitar atendimento. A equipe Fivecred orienta você sobre as modalidades e condições disponíveis.','Seu perfil de crédito','Escolha entre INSS, FGTS, CLT ou conta de luz.','Uma consulta inicial','A equipe orienta você sobre a análise e as condições do crédito.'],
 'bolsa-fivecred':['Informe seus dados e as informações do benefício para simular uma possibilidade. O resultado é ilustrativo e não representa crédito aprovado. A disponibilidade depende da análise da instituição financeira.','Dados da solicitação','Preencha seus dados pessoais e de contato no formulário.','Informações do benefício','Informe o valor recebido e o NIS, conforme os campos do formulário.'],
 'consignado-fivecred':['Informe seus dados, o tipo e o valor do benefício para uma simulação inicial. Conheça as condições e avalie como as parcelas cabem no seu planejamento.','Seus dados primeiro','Preencha os dados de contato e identificação solicitados.','Benefício e margem','Informe seu benefício e a situação da margem para a simulação.'],
 'luz-fivecred':['Preencha seus dados e as informações da conta de energia para simular. A disponibilidade depende da região, da distribuidora e da análise da instituição financeira.','Dados e endereço','Informe seus dados e o endereço relacionado à solicitação.','Sua conta de energia','Preencha as informações de titularidade e consumo do formulário.'],
 'imovel-fivecred':['Conte sobre você e seu imóvel para uma simulação inicial. A equipe explica avaliação, custos e condições antes de você decidir.','Dados da solicitação','Preencha os dados pessoais e de contato solicitados.','Informações do imóvel','Informe valor, localização e situação do imóvel, incluindo o saldo devedor quando houver.'],
 'veiculo-fivecred':['Informe seus dados e as características do veículo para simular. Entenda avaliação, valores e condições antes de escolher o próximo passo.','Dados de contato','Preencha nome, WhatsApp, CPF e e-mail no formulário.','Sobre o seu veículo','Informe modelo, ano, placa, valor estimado e situação do financiamento.']
 };
 for(const page of pages){
  const d=details[page.slug];if(d){if(page.slug==='fivecred-next')page.label='Crédito para o seu momento';page.intro=d[0];page.description=d[0];page.benefits[0]={title:d[1],text:d[2]};page.benefits[1]={title:d[3],text:d[4]};page.how=[{title:'Preencha a solicitação',text:d[2]},{title:'Conte sobre seu momento',text:d[4]},{title:page.slug==='fivecred-landing-page'?'Conheça os canais de atendimento':'Confira o próximo passo',text:page.slug==='fivecred-landing-page'?'Converse com a equipe para entender as condições e os próximos passos da análise.':'Confira os dados e continue pelo canal de atendimento do formulário. Qualquer proposta depende de análise.'}];
   page.faq=page.faq.map(item=>/CPF|NIS|dados pessoais|nome do empréstimo/.test(item.q)?{q:'Quais dados preciso informar?',a:d[2]+' '+d[4]+' Preencha apenas os campos apresentados no formulário.'}:item);
  }
  if(['fivecred-next','fivecred-landing-page'].includes(page.slug)){
   page.benefits[0]={title:'Encontre um caminho antes do cadastro',text:'Escolha objetivo, perfil e valor de interesse. Você conhece um próximo passo antes de informar seus dados.'};
   page.benefits[1]={title:'Continue com suas escolhas em mãos',text:'Conheça a página indicada, siga para o formulário ou converse no WhatsApp com seu objetivo, perfil e valor.'};
   page.how=[{title:'Conte seu objetivo',text:'Organizar as contas, realizar um projeto ou entender as opções: escolha o que combina com seu momento.'},{title:'Escolha seu perfil e valor',text:'Informe o que faz parte da sua realidade e ajuste o valor de interesse.'},{title:'Conheça seu próximo passo',text:'Veja uma opção a conhecer e decida como continuar. O direcionamento não é uma aprovação de crédito.'}];
   page.faq[0]={q:'Preciso saber qual empréstimo escolher?',a:'Não. A orientação começa com seu objetivo, seu perfil e o valor desejado. Depois você conhece uma opção e escolhe como continuar.'};
   page.faq[1]={q:'Preciso informar CPF para começar?',a:'Não. As três escolhas iniciais não pedem dados pessoais. Se continuar no formulário, os campos de identificação da modalidade serão apresentados. Para conversar no WhatsApp, pedimos nome e e-mail.'};
  }
  if(page.slug==='consignado-fivecred')page.faq=page.faq.map(item=>item.q==='O site consulta meu benefício automaticamente?'?{...item,a:'A simulação usa os dados preenchidos no formulário e parâmetros ilustrativos. Não consulta o INSS, não confirma margem disponível e não aprova um contrato.'}:item);
  if(page.type==='buyer'){page.intro='Informe seu nome, WhatsApp e o tipo de bem que procura. Converse com a Fivecred sobre disponibilidade, entrada, saldo e condições da transferência.';page.how[0]={title:'Conte o que você procura',text:'Preencha nome, WhatsApp e tipo de bem para começar o atendimento.'};page.benefits[0]={title:'Comece pelo bem que procura',text:'Informe seu nome, WhatsApp e o tipo de bem para consultar as opções com a equipe.'};page.benefits=page.benefits.map(b=>/entrada.*antes|dados pessoais|CPF/.test(b.text)?{title:b.title,text:'Converse sobre entrada, saldo a pagar e condições da transferência antes de decidir.'}:b);}
 }
};
