module.exports = function sellerPage({page, prefix, icon, esc, visualSlot, visual, simulation}) {
  const action=(label,secondary=false)=>`<a class="button ${secondary?'s-button-outline':''}" data-simulation-link href="${simulation.href(page,prefix)}">${label}${icon('arrow')}</a>`;
  const art=(type)=>type==='home'?`<svg viewBox="0 0 420 230" class="s-property-art" aria-hidden="true"><ellipse cx="220" cy="209" rx="166" ry="11" fill="#efd7c5"/><path d="M61 118 191 29l134 89" fill="#ff8a3d"/><path d="M83 114 192 41l108 74v91H83Z" fill="#fff"/><path d="m73 119 119-83 121 83" fill="none" stroke="#14243a" stroke-width="9" stroke-linejoin="round"/><path d="M178 207v-70h46v70" fill="#ff6b00"/><path d="M108 126h43v41h-43zm142 0h28v41h-28z" fill="#e0edf0" stroke="#14243a" stroke-width="4"/><path d="M129 127v39m-20-20h41m112-19v39" stroke="#14243a" stroke-width="3"/><circle cx="213" cy="177" r="3" fill="#14243a"/><path d="M330 206v-63" stroke="#14243a" stroke-width="6"/><path d="M331 102c-44 0-46 66 0 65 41-1 40-65 0-65" fill="#ed7a35"/><path d="M50 204v-35m0 12-14-12m14 5 14-13" fill="none" stroke="#52705b" stroke-width="5" stroke-linecap="round"/></svg>`:`<svg viewBox="0 0 420 230" class="s-property-art" aria-hidden="true"><ellipse cx="211" cy="203" rx="166" ry="11" fill="#efd7c5"/><path d="m57 143 41-16 42-62h124l52 65 43 17 8 42H49Z" fill="#ff7b20" stroke="#14243a" stroke-width="5" stroke-linejoin="round"/><path d="m127 126 27-44h96l35 44Z" fill="#d9eced" stroke="#14243a" stroke-width="4"/><path d="M209 84v44m-11 5v54" stroke="#14243a" stroke-width="4"/><path d="M222 145h19" stroke="#14243a" stroke-width="5" stroke-linecap="round"/><rect x="52" y="153" width="34" height="13" rx="5" fill="#fff5d7"/><rect x="334" y="151" width="25" height="12" rx="4" fill="#fff5d7"/><circle cx="115" cy="188" r="29" fill="#14243a"/><circle cx="115" cy="188" r="13" fill="#fff"/><circle cx="299" cy="188" r="29" fill="#14243a"/><circle cx="299" cy="188" r="13" fill="#fff"/><path d="M59 40h68m-93 19h55" stroke="#edb18a" stroke-width="5" stroke-linecap="round"/></svg>`;
  return `<div class="seller-page brand-page">
<section class="s-hero" aria-labelledby="seller-title">
 <div class="container s-hero-grid">
  <div class="s-hero-copy">
   <div class="s-hero-heading"><p class="s-eyebrow">${icon('document')}A Fivecred compra a sua carta contemplada</p>
    <h1 id="seller-title">${esc(page.headline)}</h1>
    <p class="s-lead">${esc(page.intro)}</p>${visual.highlights(page,icon,esc)}
   </div>
  </div>
  <div class="s-hero-form">${simulation.card(page,prefix,icon,esc)}</div>
 </div>
</section>
<div class="s-reassurance"><div class="container s-reassurance-grid">
 <div>${icon('person')}<p><strong>A decisão é sua</strong><span>Solicitar avaliação não obriga a vender.</span></p></div>
 <div>${icon('document')}<p><strong>Condições por escrito</strong><span>Valor e pagamento claros na proposta.</span></p></div>
 <div>${icon('shield')}<p><strong>Transferência orientada</strong><span>Conforme as regras da administradora.</span></p></div>
</div></div>
${visual.story(page,prefix,icon,esc)}
<section class="s-section s-modalities"><div class="container"><div class="s-section-heading"><div><p class="s-kicker">A sua carta tem uma história</p><h2>Conte qual é a sua.<br>A Fivecred avalia a compra.</h2></div><p>Comece pela modalidade, administradora e valor do crédito. Os detalhes da cota serão considerados na avaliação.</p></div>
 <div class="s-property-grid"><article class="s-property"><div>${art('home')}</div><div class="s-property-copy"><h3>Carta de imóvel</h3><p>O projeto da casa mudou? Apresente sua carta contemplada para uma avaliação.</p></div></article><article class="s-property"><div>${art('car')}</div><div class="s-property-copy"><h3>Carta de veículo</h3><p>A compra do carro ficou para depois? Conheça as condições de uma possível venda.</p></div></article></div>
 <p class="s-modalities-note">Sua carta é de outra modalidade? Você também pode informar no formulário. Toda compra está sujeita à análise.</p>
</div></section>
<section class="s-section s-how" id="como-funciona"><div class="container"><div class="s-section-heading"><div><p class="s-kicker">Do primeiro contato à sua decisão</p><h2>Você entende cada etapa<br>antes de seguir.</h2></div>${action('Solicitar avaliação',true)}</div>
 <ol class="s-steps">${page.how.map((step,i)=>`<li><div class="s-step-top"><span>${i+1}</span>${icon(['document','chat','shield'][i])}</div><h3>${esc(step.title)}</h3><p>${esc(step.text)}</p></li>`).join('')}</ol>
</div></section>
<section class="s-section s-value"><div class="container s-value-grid"><div><p class="s-kicker">O que você precisa saber sobre o valor</p><h2>Crédito da carta e preço de venda são coisas diferentes.</h2><p>A proposta considera a situação da cota, o saldo devedor, as parcelas e as condições da negociação. Você conhece o valor oferecido antes de decidir.</p><ul class="s-value-checks"><li>${icon('check')}Qual valor você receberá</li><li>${icon('check')}Como e quando será o pagamento</li><li>${icon('check')}Quais são as condições da transferência</li></ul>${simulation.sectionAction(page,prefix,icon,esc)}</div>
 <div class="s-value-visual" aria-label="Diferença entre crédito da carta e proposta de compra"><div class="s-letter"><span class="s-letter-icon">${icon('document')}</span><span>Na sua carta</span><strong>Valor do crédito</strong><p>Crédito indicado pela administradora para adquirir o bem.</p><div class="s-paper-lines" aria-hidden="true"><i></i><i></i><i></i></div></div><div class="s-offer">${icon('wallet')}<div><span>Na proposta da Fivecred</span><strong>Preço de compra da sua carta</strong><p>Valor oferecido pela cota, após a avaliação.</p></div></div><p class="s-value-caption">A proposta é apresentada para você analisar com calma.</p></div>
</div></section>
<section class="s-section s-trust" id="seguranca"><div class="container s-trust-grid"><div class="trust-heading"><p class="s-kicker">Fivecred, do seu lado na negociação</p><h2>Uma decisão importante merece uma conversa clara.</h2><p>Sua carta representa parte do seu patrimônio. Saiba com quem está falando e confira as condições antes de formalizar a venda.</p>${action('Começar pelo formulário')}</div>${visualSlot(prefix,true,page)}<ul class="s-trust-list"><li><details data-reading-panel open><summary>${icon('person')}<strong>Atendimento identificado</strong><span class="reading-toggle" aria-hidden="true">${icon('plus')}</span></summary><div class="reading-panel-body"><p>Fivecred · CNPJ 50.267.345/0001-84.<br>Endereço e canais oficiais disponíveis no rodapé.</p></div></details></li><li><details data-reading-panel open><summary>${icon('document')}<strong>Proposta explicada</strong><span class="reading-toggle" aria-hidden="true">${icon('plus')}</span></summary><div class="reading-panel-body"><p>Converse sobre valor, pagamento, documentos e responsabilidades.</p></div></details></li><li><details data-reading-panel open><summary>${icon('shield')}<strong>Respeito à sua decisão</strong><span class="reading-toggle" aria-hidden="true">${icon('plus')}</span></summary><div class="reading-panel-body"><p>Você pode tirar dúvidas e revisar a proposta antes de aceitar.</p></div></details></li></ul></div></section>
<section class="s-section s-faq" id="duvidas"><div class="container s-faq-grid"><div><p class="s-kicker">Suas dúvidas merecem resposta</p><h2>Vamos deixar<br>tudo mais claro.</h2><p>Veja o que costuma gerar dúvidas antes de vender uma carta contemplada.</p>${simulation.sectionAction(page,prefix,icon,esc)}<div class="s-question-graphic" aria-hidden="true">${icon('document')}<span>?</span></div></div><div class="faq-list">${page.faq.map((f,i)=>`<details${i===0?' open':''}><summary>${esc(f.q)}${icon('plus')}</summary><p>${esc(f.a)}</p></details>`).join('')}</div></div></section>
<section class="s-closing"><div class="container s-closing-inner"><div><p>Seus planos, sua escolha.</p><h2>Comece conhecendo uma proposta para a sua carta.</h2></div><div>${action('Quero vender minha carta')}<span>Sem compromisso. Você decide se quer continuar.</span></div></div></section>
</div>`;
};
